default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: utf8
  database: aneib_development
  pool: 5
  username: root
  password: kvhipj23

test:
  <<: *default
  database: aneib_test

production:
  <<: *default
  database: aneib_staging
  pool: 5
  username: root
  password: kvhipj23