default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: kvhipj23
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: aneib_development

test:
  <<: *default
  database: aneib_test

production:
  <<: *default
  database: aneib_production
  username: aneib
  password: kvhipj23
