# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3608a01b91230c0e80dcaeb010f82e74ef87c9fe96dbbcdf21384747eaab416c97258c4cf68073cd083ff896012f982f862647ede89a2c07a93e4a679fdb8649

test:
  secret_key_base: e24b7ed6cc447f384342ca1248f2c9a8eab7782952092c827511017a144beb305a2a83a2173f4ee56f36e6595c1b8ff56310b5d4e045e7ba6b7428b8a9dbd1db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
