# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 257fc6765501ffce6f8bd50255a891f519c921b74f4796456ec0748acb15ef22c16b547f3287cdb06ca74474ca66b198c5afd4e4ed8f5316262fb4ce9c9771a8

test:
  secret_key_base: 2d4a5a32ba15e6136bd54b8e5848bd5e04b7e8723f7bd1439b69722abdcd8d7580d4e80a6d83b881d23db90f5177e67812d843ebd8349eef842c7a4d4777ae70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 184b17cda372fc6d2d3bf23d71e967c42443761383beca50e30a44cf0cd9f9315fdc839eebe050c51375f5b811b2920b3a7a17056182cf8b80cbe2943fd41460
